name: Trigger on CV commit

on:
  repository_dispatch:
    types: [cv_master_commit]

jobs:
  build:
    name:
    
    runs-on: ubuntu-latest

    steps:
    - name: CV trigger

      run: |
        echo "repository_dispatch triggered"
