name: Trigger on CV commit

on:
  repository_dispatch:
    types: [cv_master_commit]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: dispatch trigger

    - run: |
        echo "repository_dispatch triggered"
